meta_product_name: "EasyTrip"
meta_title: "EasyTrip - Get ready to live your best life !"
meta_description: "You love adventures and surprises? EasyTrip is here to help you. Select a specific category which you would like to explore and let the app do its magic. Just sit back, relax and enjoy!"
meta_image: "og_img.jpg" # should exist in `app/assets/images/`